#ifndef SYSTEM_CONFIG_H
#define SYSTEM_CONFIG_H

#define SYSTEM_TIMER_SRC_US_SEG AM_HAL_CTIMER_TIMERA
#define SYSTEM_TIMER_SRC_US_NUM 0

#define SYSTEM_TIMER_SRC_MS_SEG AM_HAL_CTIMER_TIMERB
#define SYSTEM_TIMER_SRC_MS_NUM 0

#define SYSTEM_TIMER_COUNTER_MS_SEG AM_HAL_CTIMER_TIMERA
#define SYSTEM_TIMER_COUNTER_MS_NUM 1

#define ADC_TIMER_SEG AM_HAL_CTIMER_TIMERA
#define ADC_TIMER_NUM 3

#define ADC_MAX_RESOLUTION  14
#define ADC_MIN_RESOLUTION   8

#define PWM_MAX_RESOLUTION  16
#define PWM_MIN_RESOLUTION   8

#endif // SYSTEM_CONFIG_H
